# Generated by Django 5.2.8 on 2025-12-02 11:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('source_ip', models.GenericIPAddressField()),
                ('source_port', models.IntegerField()),
                ('payload', models.TextField()),
                ('payload_size', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Satellite Data Packet',
                'verbose_name_plural': 'Satellite Data Packets',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='receiver_sa_timesta_795f5b_idx'), models.Index(fields=['source_ip'], name='receiver_sa_source__8e7879_idx')],
            },
        ),
    ]
