# Generated by Django 5.2.8 on 2025-12-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedata',
            name='cep_radius',
            field=models.IntegerField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='decoded_payload',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='imei',
            field=models.CharField(blank=True, db_index=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='is_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='message_sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='momsn',
            field=models.IntegerField(blank=True, help_text='Mobile Originated Message Sequence Number', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='mtmsn',
            field=models.IntegerField(blank=True, help_text='Mobile Terminated Message Sequence Number', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='parse_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='payload_hex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='session_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='session_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='satellitedata',
            index=models.Index(fields=['imei'], name='receiver_sa_imei_f786cd_idx'),
        ),
    ]
