# Generated by Django 5.2.8 on 2025-12-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiver', '0002_satellitedata_cep_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellitedata',
            name='air_temperature',
            field=models.FloatField(blank=True, help_text='Air temperature in °C', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='barometric_pressure',
            field=models.FloatField(blank=True, help_text='Pressure in hPa', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='eucaws_decode_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='eucaws_timestamp',
            field=models.DateTimeField(blank=True, help_text='Timestamp from EUCAWS payload', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='is_eucaws_decoded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='relative_humidity',
            field=models.FloatField(blank=True, help_text='Humidity in %', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='sea_temperature',
            field=models.FloatField(blank=True, help_text='Sea temperature in °C', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='wind_direction',
            field=models.FloatField(blank=True, help_text='Wind direction in degrees', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='wind_speed_knots',
            field=models.FloatField(blank=True, help_text='Wind speed in knots', null=True),
        ),
        migrations.AddField(
            model_name='satellitedata',
            name='wind_speed_ms',
            field=models.FloatField(blank=True, help_text='Wind speed in m/s', null=True),
        ),
    ]
